<?php
declare(strict_types=1);
/**
 * This file is part of application TwitterMetrics
 * @copyright (c) 2021 Lenoch (www.lenoch.cz)
 * @author        Milan Lysak <mlysak@email.cz>
 */

namespace App\Model\Manager;

use App\Exception\ApiException;
use App\Exception\TweetManagerException;
use App\Model\Entity\TweetEntity;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Exception\ORMException;
use App\Api\TwitterApi;

/**
 * Class TweetManager
 * @package App\Model\Manager
 */
class TweetManager extends EntityRepository
{
    /** @var TwitterApi */
    protected TwitterApi $twitterApi;

    /** @var EntityManager */
    protected EntityManager $em;

    /** @var EntityRepository */
    protected EntityRepository $repository;

    /** @var string */
    protected string $entity;

    /**
     * @param object $entity
     * @throws TweetManagerException
     */
    public function persist(object $entity): void
    {
        try {
            $this->em->persist($entity);
        } catch (\Exception $e) {
            throw new TweetManagerException($e);
        }
    }


    /**
     * @param object|object[]|null $entity
     * @throws TweetManagerException|\Doctrine\ORM\ORMException
     */
    public function flush(object|array $entity = null): void
    {
        try {
            $this->em->flush($entity);
        } catch (ORMException $e) {
            throw new TweetManagerException('Unexpected database fail', '0', $e);
        }
    }

    /**
     * @throws ApiException
     */
    public function findTweet(string $criteria, ?array $orderBy = null, $limit = null, $offset = null)
    {
        return $this->twitterApi->connectTwitter($criteria);

//        return parent::findBy($criteria, $orderBy, $limit, $offset); // TODO: Change the autogenerated stub
    }
}